In [4]:
#Numpy referes to Numerical Python
# It is a package for data analysis and scientific computing with Python.
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
arr1.view()

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [8]:
#2d array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)
arr2.view()
print(type(arr2))

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>


In [16]:
#random number using random module
import random
print(np.random.randint(2,5,6))#np.random.randint(start,end,count)

[3 3 4 3 4 3]


In [27]:
arr3=np.array([[1,23,4,5,6],[4,5,6,3,3],[53,6,7,8,9]])
arr3
print(type(arr3))
print(np.shape(arr3))
print(np.size(arr3))
print(np.ndim(arr3))
print(arr3.dtype)
print(arr3.astype(float))

<class 'numpy.ndarray'>
(3, 5)
15
2
int32
[[ 1. 23.  4.  5.  6.]
 [ 4.  5.  6.  3.  3.]
 [53.  6.  7.  8.  9.]]


In [32]:
print(np.add(3,4))
print(np.subtract(5,3))
print(np.multiply(3,4))
print(np.divide(6,3))
print(np.mod(6,4))
print(np.power(3,3))
print(np.sqrt(91))

7
2
12
2.0
2
27
9.539392014169456


In [40]:
arr2=np.array([2,3,4,5,6])
print(np.concatenate([arr1,arr2],axis=0))#axis=0 represents concatenate according to the rows and it is default

[1 2 3 4 5 2 3 4 5 6]


In [42]:
arr3=np.array([[1,4,5,3,2],[5,5,6,2,3]])
arr4=np.array([[5,3,4,6,7],[7,9,0,8,7]])
print(np.concatenate([arr3,arr4],axis=1))#axis=1 represents concatenate according to the columns

[[1 4 5 3 2 5 3 4 6 7]
 [5 5 6 2 3 7 9 0 8 7]]


In [51]:
print(arr1)
print(np.append(arr1,4))
print(np.insert(arr1,5,6))#np.insert(array_name,index,value)
print(np.delete(arr1,2))

[1 2 3 4 5]
[1 2 3 4 5 4]
[1 2 3 4 5 6]
[1 2 4 5]


In [58]:
arr4=np.array([3,2,5,4,6,4])
print(np.sort(arr4))
print(np.sum(arr4))
print(np.min(arr4))
print(np.max(arr4))
print(np.where(arr4==4))
print(np.where(arr4==2))
print(np.mean(arr4))


[2 3 4 4 5 6]
24
2
6
(array([3, 5], dtype=int64),)
(array([1], dtype=int64),)
4.0
